name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install pytest tqdm matplotlib numpy torchsummary
        pip install -e .
        
    - name: Run pre-training tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) python -m pytest tests/test_model_structure.py -v
        
    - name: Train model
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) python train.py
        
    - name: Run post-training tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) python -m pytest tests/test_model_performance.py -v
        
    - name: Upload training artifacts
      uses: actions/upload-artifact@v4
      with:
        name: training-results
        path: |
          images/
          logs/